# Generated by Django 4.2.5 on 2024-07-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NUMARTISAPP', '0002_demandeservice_delete_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeService1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question3', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('demande', models.CharField(max_length=100, null=True)),
                ('delai', models.CharField(max_length=100, null=True)),
                ('heure', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeService3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=100)),
                ('question2', models.CharField(max_length=100)),
                ('question3', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ville', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=2000)),
                ('budjet', models.CharField(max_length=100)),
                ('disponibilite', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='oui', max_length=10)),
                ('contact_preference', models.CharField(choices=[('telephone', 'Téléphone'), ('email', 'Email')], default='email', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='DemandeService',
        ),
    ]
