# Generated by Django 4.2.5 on 2024-07-24 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NUMARTISAPP', '0003_demandeservice1_demandeservice3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeservice1',
            name='question3',
        ),
    ]
