# Generated by Django 4.2.5 on 2024-07-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NUMARTISAPP', '0004_remove_demandeservice1_question3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeservice1',
            name='delai',
            field=models.CharField(choices=[('30 minutes', '30 minutes'), ('1 heure', '1 heure'), ('2 heures', '2 heures'), ('1 jour', '1 jour'), ('2 jours', '2 jours'), ('5 jours', '5 jours')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demandeservice1',
            name='heure',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
