# Generated by Django 4.2.5 on 2024-07-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NUMARTISAPP', '0005_alter_demandeservice1_delai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeservice1',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice1',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice1',
            name='tel',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice1',
            name='ville',
            field=models.CharField(choices=[('Abidjan', 'Abidjan'), ('Yamoussoukro', 'Yamoussoukro'), ('Bouake', 'Bouake'), ('Daloa', 'Daloa'), ('San-Pedro', 'San-Pedro'), ('San-Rémi', 'San-Rémi'), ('Sassandra', 'Sassandra'), ('Soubre', 'Soubre'), ('Toumodi', 'Toumodi')], max_length=100, null=True),
        ),
    ]
