# Generated by Django 4.2.5 on 2024-07-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NUMARTISAPP', '0006_demandeservice1_address_demandeservice1_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeservice1',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=20000000, null=True),
        ),
        migrations.AddField(
            model_name='demandeservice1',
            name='non',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='demandeservice1',
            name='oui',
            field=models.BooleanField(default=True),
        ),
    ]
