# Generated by Django 4.2.5 on 2024-07-24 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NUMARTISAPP', '0007_demandeservice1_budget_demandeservice1_non_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandeservice1',
            old_name='non',
            new_name='indisponibilite',
        ),
        migrations.RemoveField(
            model_name='demandeservice1',
            name='oui',
        ),
    ]
