# Generated by Django 4.2.5 on 2024-08-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NUMARTISAPP', '0008_rename_non_demandeservice1_indisponibilite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeservice1',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
